import type { CatalogItem } from '../../types/marketplaceV2'

const CATALOG: CatalogItem[] = [
  {
    catalogItemId: 'ba8671aa-7481-43e5-a1ac-f2b73433a315',
    sku: 'WP-4',
    itemType: 'WORD_PACK',
    itemName: '4 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:FOUR_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: 'b1b96d0e-5b1a-403e-80be-88f3d2bae873',
    sku: 'WP-11-EXP',
    itemType: 'WORD_PACK',
    itemName: '11 Letter Expansion',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:ELEVEN_LETTER_EXPANSION',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: '7f06b10e-d52a-4ae3-b77f-a7e9a7c5e5fb',
    sku: 'WP-12',
    itemType: 'WORD_PACK',
    itemName: '12 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:TWELVE_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: 'b8c73f14-79ad-4495-9fd9-a4be65d5fcbc',
    sku: 'WP-13',
    itemType: 'WORD_PACK',
    itemName: '13 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:THIRTEEN_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: '3159552d-8c96-4bb5-aafa-ebf36aa5a2c2',
    sku: 'WP-14',
    itemType: 'WORD_PACK',
    itemName: '14 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:FOURTEEN_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: 'fef67eba-96db-4f5e-8b25-81487a1dbc9d',
    sku: 'WP-15',
    itemType: 'WORD_PACK',
    itemName: '15 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:FIFTEEN_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: '1ee2de50-072f-4718-b8ac-7663f3069f2e',
    sku: 'WP-16',
    itemType: 'WORD_PACK',
    itemName: '16 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:SIXTEEN_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: '80e197a9-0829-4074-8e85-a88e6e8b7ea0',
    sku: 'WP-17',
    itemType: 'WORD_PACK',
    itemName: '17 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:SEVENTEEN_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: '425c96ab-beff-40ef-9774-feb6db135644',
    sku: 'WP-18',
    itemType: 'WORD_PACK',
    itemName: '18 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:EIGHTEEN_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: '1d348c05-c51e-4ea3-a888-d4823436704f',
    sku: 'WP-19',
    itemType: 'WORD_PACK',
    itemName: '19 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:NINETEEN_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: '6e66a620-8e17-4f75-aa0b-1c282aafb9d8',
    sku: 'WP-20',
    itemType: 'WORD_PACK',
    itemName: '20 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:TWENTY_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: '72215e5b-6638-4388-84bc-55dcd36c0e05',
    sku: 'WP-21',
    itemType: 'WORD_PACK',
    itemName: '21 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:TWENTYONE_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: 'db526774-11da-47de-b410-5b47a4168db8',
    sku: 'WP-22',
    itemType: 'WORD_PACK',
    itemName: '22 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:TWENTYTWO_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: 'ab14511c-f2ac-4b16-a8ef-7cb8ed61a2cc',
    sku: 'WP-23',
    itemType: 'WORD_PACK',
    itemName: '23 Letter Pack',
    priceCoins: 1000,
    entitlementKey: 'WORD_PACK:TWENTYTHREE_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
  {
    catalogItemId: '3d3ff93b-65c1-4d36-902e-3a889c71ac86',
    sku: 'WP-12-23',
    itemType: 'WORD_PACK',
    itemName: '12-23 Letter Mega Pack',
    priceCoins: 10000,
    entitlementKey: 'WORD_PACK:TWELVE_TO_TWENTYTHREE_LETTER',
    entitlementType: 'WORD_PACK',
    isPurchasable: true,
  },
]

export function getCatalogItemsByIds(ids: string[]): CatalogItem[] {
  const map = new Map(CATALOG.map(item => [item.catalogItemId, item]))
  return ids.map(id => map.get(id)).filter(Boolean) as CatalogItem[]
}