insert into _items (
  id,
  name,
  coin_price,
  real_price,
  description,
  purchasable_with_coins,
  purchasable_with_money,
  discontinued,
  type,
  game,
  rarity,
  item_image,
  marketplace_image
)
values
(
  'eea2ee39-7ff5-4cfc-906b-608d01555afa',
  'Cyberpunk Theme',
  1000,
  0.99,
  'A neon-soaked 80s cyberpunk theme for the Wordrama game board.',
  true,
  true,
  false,
  'THEME',
  'WORDLE',
  'premium',
  null,
  null
),
(
  'c42e21b8-e3e2-487b-9307-698063f29dcd',
  'Miami Vice Theme',
  1000,
  0.99,
  'A bright retro pink-and-cyan theme inspired by 80s nightlife.',
  true,
  true,
  false,
  'THEME',
  'WORDLE',
  'premium',
  null,
  null
),
(
  'db984ab5-f0a9-43a9-9800-702150de76f5',
  'Galaxy Theme',
  1000,
  0.99,
  'A deep space theme with violet, indigo, and cosmic glow.',
  true,
  true,
  false,
  'THEME',
  'WORDLE',
  'premium',
  null,
  null
),
(
  '8642cdb8-7f8e-4c58-be01-3f9d5362326d',
  'Ice Theme',
  1000,
  0.99,
  'A crisp icy theme with cool cyan tones and frosted styling.',
  true,
  true,
  false,
  'THEME',
  'WORDLE',
  'premium',
  null,
  null
),
(
  '4085cec0-6c84-4732-b70c-a80938afe0a5',
  'Lava Theme',
  1000,
  0.99,
  'A molten lava theme with fiery red and orange accents.',
  true,
  true,
  false,
  'THEME',
  'WORDLE',
  'premium',
  null,
  null
),
(
  'a0144a0f-6867-4140-a520-f64375f35990',
  'Forest Theme',
  1000,
  0.99,
  'A lush forest theme with deep greens and glowing lime accents.',
  true,
  true,
  false,
  'THEME',
  'WORDLE',
  'premium',
  null,
  null
),
(
  '7855a094-b1df-49c5-abf0-622e651df69a',
  'Pirate Theme',
  1000,
  0.99,
  'A rugged pirate theme with dark wood, stone, and golden accents.',
  true,
  true,
  false,
  'THEME',
  'WORDLE',
  'premium',
  null,
  null
),
(
  '49a35b50-db84-4854-847e-e9610874f878',
  'Arcade Theme',
  1000,
  0.99,
  'A retro arcade theme with neon highlights and pixel-era energy.',
  true,
  true,
  false,
  'THEME',
  'WORDLE',
  'premium',
  null,
  null
),
(
  'c58ed56e-3891-44c6-b195-b9d1c8bbe980',
  'Synthwave Theme',
  1000,
  0.99,
  'A synthwave theme with bold pinks, purples, cyan accents, and sunset energy.',
  true,
  true,
  false,
  'THEME',
  'WORDLE',
  'premium',
  null,
  null
)
on conflict (id) do update set
  name = excluded.name,
  coin_price = excluded.coin_price,
  real_price = excluded.real_price,
  description = excluded.description,
  purchasable_with_coins = excluded.purchasable_with_coins,
  purchasable_with_money = excluded.purchasable_with_money,
  discontinued = excluded.discontinued,
  type = excluded.type,
  game = excluded.game,
  rarity = excluded.rarity,
  item_image = excluded.item_image,
  marketplace_image = excluded.marketplace_image;
