insert into public._challenges (
  id,
  name,
  description,
  unlocks_at_level,
  coins_to_unlock,
  item_reward,
  coin_reward,
  xp_reward,
  game,
  is_game_specific,
  notification_message,
  how_to_get,
  comparator,
  param,
  value,
  is_active,
  avatar_entitlement_key
)
values
  (
    '4a73b85a-9e40-4ed4-a55d-a7de4ce20f8a',
    'Daily Champion',
    'Finish #1 on any Daily leaderboard',
    1,
    0,
    null,
    0,
    0,
    null,
    false,
    'Achievement "Daily Champion": Daily Champion crown unlocked',
    'Finish #1 on any Daily leaderboard',
    null,
    null,
    null,
    true,
    'AVATAR:CROWN_DAILY_CHAMPION'
  ),
  (
    '3beaa47f-5638-4ba2-a42a-b45f3cb5b6bf',
    'Weekly Champion',
    'Finish #1 on any Weekly leaderboard',
    1,
    0,
    null,
    0,
    0,
    null,
    false,
    'Achievement "Weekly Champion": Weekly Champion crown unlocked',
    'Finish #1 on any Weekly leaderboard',
    null,
    null,
    null,
    true,
    'AVATAR:CROWN_WEEKLY_CHAMPION'
  ),
  (
    '0af08641-fbe3-454d-b21f-8f2cbdfdb28a',
    'Monthly Champion',
    'Finish #1 on any Monthly leaderboard',
    1,
    0,
    null,
    0,
    0,
    null,
    false,
    'Achievement "Monthly Champion": Monthly Champion crown unlocked',
    'Finish #1 on any Monthly leaderboard',
    null,
    null,
    null,
    true,
    'AVATAR:CROWN_MONTHLY_CHAMPION'
  ),
  (
    '95bb2ed7-c13b-4231-9625-e403725a5693',
    'Yearly Champion',
    'Finish #1 on any Yearly leaderboard',
    1,
    0,
    null,
    0,
    0,
    null,
    false,
    'Achievement "Yearly Champion": Yearly Champion crown unlocked',
    'Finish #1 on any Yearly leaderboard',
    null,
    null,
    null,
    true,
    'AVATAR:CROWN_YEARLY_CHAMPION'
  )
on conflict (id) do nothing;
