export const FEATURES = {
  TEAMS_CREATE: 'FEATURE:TEAMS_CREATE',
  TEAMS_MULTI_JOIN: 'FEATURE:TEAMS_MULTI_JOIN',

  AVATAR_UPLOAD: 'FEATURE:AVATAR_UPLOAD',

  UI_CUSTOMIZATION: 'FEATURE:UI_CUSTOMIZATION',

  PVP_PLAY: 'FEATURE:PVP_PLAY',
} as const;

export type FeatureKey = typeof FEATURES[keyof typeof FEATURES];
