import { FEATURES } from './features';
import { SUBSCRIPTIONS } from './subscriptions';

export const SUBSCRIPTION_ENTITLEMENTS = {
  [SUBSCRIPTIONS.PLUS]: [
    FEATURES.UI_CUSTOMIZATION,
    FEATURES.AVATAR_UPLOAD,
  ],

  [SUBSCRIPTIONS.CREATOR]: [
    FEATURES.UI_CUSTOMIZATION,
    FEATURES.AVATAR_UPLOAD,
    FEATURES.TEAMS_CREATE,
    FEATURES.TEAMS_MULTI_JOIN,
  ],
} as const;
