import { FEATURES } from './features';
import { SUBSCRIPTIONS } from './subscriptions';

const PREMIUM_THEMES = [
  'THEME:CYBERPUNK',
  'THEME:MIAMI_VICE',
  'THEME:GALAXY',
  'THEME:ICE',
  'THEME:LAVA',
  'THEME:FOREST',
  'THEME:CABIN',
  'THEME:PIRATE',
  'THEME:ARCADE',
  'THEME:SYNTHWAVE',
] as const;

export const SUBSCRIPTION_ENTITLEMENTS = {
  [SUBSCRIPTIONS.PLUS]: [
    FEATURES.UI_CUSTOMIZATION,
    FEATURES.TEAMS_MULTI_JOIN,
    ...PREMIUM_THEMES,
  ],

  [SUBSCRIPTIONS.CREATOR]: [
    FEATURES.UI_CUSTOMIZATION,
    FEATURES.AVATAR_UPLOAD,
    FEATURES.TEAMS_CREATE,
    FEATURES.TEAMS_MULTI_JOIN,
    ...PREMIUM_THEMES,
  ],
} as const;
