import { FEATURES } from './features';
import { SUBSCRIPTIONS } from './subscriptions';

const PREMIUM_THEMES = [
  'THEME:CYBERPUNK',
  'THEME:MIAMI_VICE',
  'THEME:GALAXY',
  'THEME:ICE',
  'THEME:LAVA',
  'THEME:FOREST',
  'THEME:CABIN',
  'THEME:PIRATE',
  'THEME:ARCADE',
  'THEME:SYNTHWAVE',
] as const;

const PREMIUM_WORD_PACKS = [
  'WORD_PACK:FOUR_LETTER',
  'WORD_PACK:FIVE_LETTER_CRAZY',
  'WORD_PACK:ELEVEN_LETTER_EXPANSION',
  'WORD_PACK:TWELVE_TO_TWENTYTHREE_LETTER',
  'WORD_PACK:TWELVE_LETTER',
  'WORD_PACK:THIRTEEN_LETTER',
  'WORD_PACK:FOURTEEN_LETTER',
  'WORD_PACK:FIFTEEN_LETTER',
  'WORD_PACK:SIXTEEN_LETTER',
  'WORD_PACK:SEVENTEEN_LETTER',
  'WORD_PACK:EIGHTEEN_LETTER',
  'WORD_PACK:NINETEEN_LETTER',
  'WORD_PACK:TWENTY_LETTER',
  'WORD_PACK:TWENTYONE_LETTER',
  'WORD_PACK:TWENTYTWO_LETTER',
  'WORD_PACK:TWENTYTHREE_LETTER',
] as const;

export const SUBSCRIPTION_ENTITLEMENTS = {
  [SUBSCRIPTIONS.PLUS]: [
    FEATURES.UI_CUSTOMIZATION,
    FEATURES.TEAMS_MULTI_JOIN,
    ...PREMIUM_THEMES,
    ...PREMIUM_WORD_PACKS,
  ],

  [SUBSCRIPTIONS.CREATOR]: [
    FEATURES.UI_CUSTOMIZATION,
    FEATURES.AVATAR_UPLOAD,
    FEATURES.TEAMS_CREATE,
    FEATURES.TEAMS_MULTI_JOIN,
    ...PREMIUM_THEMES,
    ...PREMIUM_WORD_PACKS,
  ],
} as const;
