/** @type {import('next-sitemap').IConfig} */

module.exports = {
  siteUrl: 'https://wordrama.io',
  changefreq: 'daily',
  priority: 0.7,
  sitemapSize: 5000,
  generateRobotsTxt: true,
  exclude: [],
  alternateRefs: [
    //{
    //  href: 'https://es.example.com',
    //  hreflang: 'es',
    //},
  ],
  // Default transformation function
  transform: async (config, path) => {
    return {
      loc: path, // => this will be exported as http(s)://<config.siteUrl>/<path>
      changefreq: config.changefreq,
      priority: config.priority,
      lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
      alternateRefs: config.alternateRefs ?? [],
    }
  },
  additionalPaths: async (config) => [
    await config.transform(config, '/free-play'),
    await config.transform(config, '/free-play/five-letter'),
    await config.transform(config, '/free-play/six-letter'),
    await config.transform(config, '/free-play/seven-letter'),
    await config.transform(config, '/free-play/eight-letter'),
    await config.transform(config, '/free-play/nine-letter'),
    await config.transform(config, '/free-play/ten-letter'),
    await config.transform(config, '/free-play/eleven-letter'),
    await config.transform(config, '/free-play/5-letter'),
    await config.transform(config, '/free-play/6-letter'),
    await config.transform(config, '/free-play/7-letter'),
    await config.transform(config, '/free-play/8-letter'),
    await config.transform(config, '/free-play/9-letter'),
    await config.transform(config, '/free-play/10-letter'),
    await config.transform(config, '/free-play/11-letter'),
    await config.transform(config, '/free-play/FIVE_LETTER'),
    await config.transform(config, '/free-play/SIX_LETTER'),
    await config.transform(config, '/free-play/SEVEN_LETTER'),
    await config.transform(config, '/free-play/EIGHT_LETTER'),
    await config.transform(config, '/free-play/NINE_LETTER'),
    await config.transform(config, '/free-play/TEN_LETTER'),
    await config.transform(config, '/free-play/ELEVEN_LETTER'),
    await config.transform(config, '/privacy-policy'),
    await config.transform(config, '/shipping-policy'),
    await config.transform(config, '/returns-policy'),
    await config.transform(config, '/terms-of-use'),
    await config.transform(config, '/cookies'),
    await config.transform(config, '/disclaimer'),
    await config.transform(config, '/games'),
    await config.transform(config, '/games/wordrama'),
    await config.transform(config, '/games/wordrama/custom'),
    await config.transform(config, '/games/wordrama/join'),
    await config.transform(config, '/leaderboard/wordle'),
    await config.transform(config, '/leaderboard/wordle/daily'),
    await config.transform(config, '/leaderboard/wordle/weekly'),
    await config.transform(config, '/leaderboard/wordle/monthly'),
    await config.transform(config, '/leaderboard/wordle/yearly'),
    await config.transform(config, '/marketplace'),
    await config.transform(config, '/marketplace/all-items'),
    await config.transform(config, '/marketplace/avatars'),
    await config.transform(config, '/marketplace/word-packs'),
    await config.transform(config, '/achievements'),
    await config.transform(config, '/about'),
    await config.transform(config, '/friends'),
    await config.transform(config, '/friends/add'),
    await config.transform(config, '/friends/requests'),
    await config.transform(config, '/friends/sent-requests'),
    await config.transform(config, '/teams'),
    await config.transform(config, '/teams/join'),
    await config.transform(config, '/teams/my-team'),
    await config.transform(config, '/settings'),
    await config.transform(config, '/settings/profile'),
    await config.transform(config, '/player/00f24b07-bb8d-4f47-ac22-41a9c4529528'),
    await config.transform(config, '/player/031ee52f-f56d-47a0-9a35-92389ab50701'),
    await config.transform(config, '/player/035e83e8-ef90-48d8-b9eb-e6c83c1f04b3'),
    await config.transform(config, '/player/03610e1c-9e6b-4d05-a389-282ec53d77a0'),
    await config.transform(config, '/player/048e7611-558f-414e-9288-d6a653cba81e'),
    await config.transform(config, '/player/09b2bdd8-7137-417d-bcc0-a53d631876c0'),
    await config.transform(config, '/player/0c260425-cd59-4308-b98f-72419d03b5eb'),
    await config.transform(config, '/player/0d8eb40a-06e3-4e73-af77-21f92c34d1b7'),
    await config.transform(config, '/player/0f1dcb98-179d-44f3-a435-aa1c76359a5c'),
    await config.transform(config, '/player/102095b8-e5c6-4e1d-838f-b8c79915b933'),
    await config.transform(config, '/player/12ed1b8d-f475-470d-b86b-486334012c59'),
    await config.transform(config, '/player/1398e67f-bda6-44ec-aab2-da6c1d8cd12c'),
    await config.transform(config, '/player/14a2ef12-ab39-4f7e-ad26-8f9abc561aa1'),
    await config.transform(config, '/player/15257484-3d59-42a3-b877-5def0aef1f22'),
    await config.transform(config, '/player/155ca099-5c4e-452c-a72f-dc30a355abc7'),
    await config.transform(config, '/player/159b1992-f5e5-41f5-99fb-2d08eb050503'),
    await config.transform(config, '/player/15aad6bb-108a-423b-a62d-2d02d9aa22b7'),
    await config.transform(config, '/player/16177779-7359-41d0-9d6a-f372fded00c6'),
    await config.transform(config, '/player/176ab572-774e-45a5-9990-cc8e0d1dd8d4'),
    await config.transform(config, '/player/176f0da3-b043-47ae-ab35-fe82e6451ded')
  ],
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        allow: '/',
      },
      //{
       // userAgent: 'test-bot',
       // allow: ['/path', '/path-2'],
      //},
    ],
    additionalSitemaps: [
      //'https://example.com/my-custom-sitemap-1.xml',
    ],
  },
}
